### ISSUE TITLE
Minor issue on requirements, name for the method?

### ISSUE THREAD

**Issue by dscarmo** [RiccardoBiondi/segmentation#7]
Hello,

First of all I would like to congratulate the organization of your code base and how everything is laid out, this is very good.

One small thing, the installed requirements in a new environment are not correct and some libraries are missing causing import errors, like lungmask and others I don't remember now. 

Additionally, your method will be included in a publication, do you have any preferred name for the method or should I just use Biondi et al.? 

Thank you

**Comment by RiccardoBiondi** [comment]
Hello, 
thank you very much! I’m glad you found this method useful in your work! 
I will chek the installation requirements! Regarding lungmask , it is an other project by JoHof, so you have to refer to its repo for the installation. 
Regarding the citation, maybe Biondi, Curti et al. could be better, since we share the autorship for the method!
Thank you!

**Comment by dscarmo** [comment]
Ok! 

You could add lungmask to the requirements as git+https://github.com/JoHof/lungmask, that's what I do and it works!
